# Generated by Django 3.2.1 on 2021-05-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=25)),
                ('staff_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.IntegerField()),
                ('experience', models.CharField(max_length=10)),
                ('qualification', models.TextField(max_length=10)),
                ('department', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25)),
                ('student_email', models.EmailField(max_length=254)),
                ('ssc_marks', models.IntegerField()),
                ('inter_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('department', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='pictures/')),
                ('father_name', models.CharField(max_length=25)),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentapplication')),
            ],
        ),
    ]
