# Generated by Django 3.2.1 on 2021-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
    ]
