# Generated by Django 3.2.1 on 2021-05-07 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_alter_studentregistration_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_mob', models.IntegerField()),
                ('experience', models.CharField(max_length=10)),
                ('qualification', models.TextField(max_length=10)),
                ('staff_dept', models.CharField(max_length=25)),
                ('staff_pic', models.ImageField(upload_to='', verbose_name='pictures/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('department', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='pictures/')),
                ('father_name', models.CharField(max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffRegistration',
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
